# Generated by Django 5.2.1 on 2025-05-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='gold_drop',
            new_name='syscred_drop',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='gold',
            new_name='syscred',
        ),
    ]
