# Generated by Django 5.2.1 on 2025-05-23 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_customuser_managers_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hacker_class',
        ),
        migrations.RemoveField(
            model_name='player',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='player',
            name='health',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_turn_reset',
        ),
        migrations.RemoveField(
            model_name='player',
            name='max_health',
        ),
        migrations.RemoveField(
            model_name='player',
            name='title',
        ),
        migrations.RemoveField(
            model_name='player',
            name='turns_remaining',
        ),
        migrations.AddField(
            model_name='customuser',
            name='faction',
            field=models.CharField(blank=True, choices=[('white_hat', 'White Hat'), ('black_hat', 'Black Hat'), ('grey_hat', 'Grey Hat'), ('nullsec', 'NullSec'), ('init6', 'Init6'), ('obfuscated', 'The Obfuscated'), ('keepers', 'The Keepers')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='handle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='critical_chance',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='dialogue',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='special_effect',
            field=models.CharField(blank=True, default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enemy',
            name='syscred_drop',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='xp_reward',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='achievements',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='syscred',
            field=models.IntegerField(default=0),
        ),
    ]
