# Generated by Django 5.2.1 on 2025-05-23 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='critical_chance',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='dialogue',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='type',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.AddField(
            model_name='enemy',
            name='damage',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemy',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='hacker_class',
            field=models.CharField(default='Script Kiddie', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='last_turn_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='turns_remaining',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faction',
            field=models.CharField(choices=[('white_hat', 'White Hat'), ('black_hat', 'Black Hat'), ('grey_hat', 'Grey Hat'), ('nullsec', 'NullSec'), ('init6', 'Init6'), ('obfuscated', 'The Obfuscated'), ('keepers', 'The Keepers')], default='grey_hat', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='handle',
            field=models.CharField(default='default_user', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enemy',
            name='special_effect',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='syscred_drop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='xp_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='achievements',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='player',
            name='syscred',
            field=models.IntegerField(default=50),
        ),
    ]
