# Generated by Django 5.2.1 on 2025-05-27 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_customuser_title_remove_enemy_critical_chance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='special_effect',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='syscred_drop',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='xp_reward',
        ),
        migrations.RemoveField(
            model_name='player',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hacker_class',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faction',
            field=models.CharField(choices=[('white_hat', 'White Hat'), ('black_hat', 'Black Hat'), ('grey_hat', 'Grey Hat'), ('nullsec', 'NullSec'), ('init6', 'Init6'), ('obfuscated', 'The Obfuscated'), ('keepers', 'The Keepers')], default='grey_hat', max_length=20),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='damage',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('is_safe_zone', models.BooleanField(default=False)),
                ('connections', models.ManyToManyField(blank=True, to='game.location')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.location'),
        ),
    ]
